name: example
description: A new Flutter project.

publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # riverpod
  flutter_hooks: ^0.18.2+1
  hooks_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1

  # freezed
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1

  # platform
  go_router: ^7.1.1
  package_info: ^2.0.2
  upgrader: ^7.0.1
  url_launcher: ^6.1.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  envied: ^0.3.0+3
  isar: ^3.1.0+1
  # network

  # ui

  # flutter_svg: ^1.0.3

  # firebase

  # utils

  # collection: ^1.16.0
  dartz: ^0.10.1
  intl: any
  # recase: ^4.1.0
  timeago: ^3.3.0
  uuid: ^3.0.7
  validators: ^3.0.0
  value:
    git:
      url: https://github.com/adriank/value.git
      ref: v0.0.9
  diagnosticable:
    git:
      url: https://github.com/adriank/diagnosticable.git
      ref: v0.0.8
  path_provider: ^2.0.15
  # rxdart: ^0.27.7

  # mini packages
  nx_localizations:
    git:
      url: https://github.com/sequrify-io/nx_localizations.git
      ref: v0.0.2
  nx_main_screen:
    git:
      url: https://github.com/sequrify-io/nx_main_screen.git
      ref: v0.0.7

  nx_sequrify:
    git:
      url: https://github.com/sequrify-io/nx_sequrify.git
      ref: v0.0.9

  nx_local_notifications:
    git:
      url: https://github.com/sequrify-io/nx_local_notifications.git
      ref: v0.0.4

  nx_ui:
     path: "../"
     
  flutter_svg: ^2.0.6
  firebase_ui_localizations: ^1.5.0
  ionicons: ^0.2.2
  # misc

  # font_awesome_flutter: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  build_runner: ^2.4.4
  json_serializable: ^6.7.0
  dart_code_metrics: ^5.0.1
  freezed: ^2.3.4
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.1
  riverpod_generator: ^2.2.3
  isar_generator: ^3.1.0+1
  envied_generator:

flutter_intl:
  enabled: true
  class_name: AppLocalizations
  main_locale: en
  arb_dir: assets/l10n
  output_dir: lib/generated

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/image/app_icon.png"

