name: nx_ui
description: A new Flutter package project.
version: 0.0.1


environment:
  sdk: '>=3.0.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  hooks_riverpod: ^2.4.0
  shimmer_animation: ^2.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/icon-arrow-right-button-white.png
    - assets/icon-big-ok.png
    - assets/icon-big-failed.png
    - assets/icon-info.png
    - assets/button-close@2x.png

